apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: hell_world_app_ingress
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`X.X.X.X`)
      kind: Rule
      services:
        - name: hell_world_app
          port: 80
  tls:
    certResolver: le