---
- name: Update and install common packages
  apt:
    update_cache: yes
    name: "{{ item }}"
    state: present
  loop:
    - curl
    - git
    - python3
    - python3-pip
    - apt-transport-https
    - ca-certificates
    - software-properties-common
    - gnupg2
    - lsb-release

- name: Install Docker GPG key and repository
  shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
    add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

- name: Install Docker
  apt:
    name: docker-ce
    state: present
    update_cache: yes

- name: Install Minikube
  shell: |
    curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    chmod +x minikube
    mv minikube /usr/local/bin/

- name: Install kubectl
  shell: |
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    chmod +x kubectl
    mv kubectl /usr/local/bin/