apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-view-role-binding
  namespace: dev
subjects:
  - kind: User
    name: developer-user   
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: developer-view-role
  apiGroup: rbac.authorization.k8s.io