apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-app
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-app
  template:
    metadata:
      labels:
        app: hello-world-app
    spec:
      containers:
      - name: hello-world-app
        image: vknysh79/hello_world:latest
        ports:
        - containerPort: 8080