apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello_world_app
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello_world_app
  template:
    metadata:
      labels:
        app: hello_world_app
    spec:
      containers:
      - name: hello_world_app
        image: vknysh79/hello_world:latest
        ports:
        - containerPort: 8080