apiVersion: v1
kind: Service
metadata:
  name: hello_world_app-service
  namespace: argocd
spec:
  selector:
    app: hello_world_app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080