apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: hello-world-app
  ports:
    - port: 8080       # Port your app listens on
      targetPort: 8081  # Port exposed by your pod
      nodePort: 30007   # Port exposed on the node (range: 30000-32767)


# apiVersion: v1
# kind: Service
# metadata:
#   name: hello-world-service
#   namespace: default
# spec:
#   type: LoadBalancer
#   selector:
#     app: hello-world-app
#   ports:
#     - port: 8080        # Service port
#       targetPort: 8081  # Port on the pod






